# name of workflow
name: CI

# event that trigger workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  CI: #job id
    runs-on: ubuntu-latest
    # cancel in-progress workflow when multiple workflow using same group
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    # steps to execute job, the following contains several execution steps 
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: "Add NPM secrets"
        shell: bash
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.DEPLOY_TOKEN  }}" >> ${{ github.workspace }}/.npmrc
          cat .npmrc

      - name: "Install dependencies"
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn workspace @mv-community/solidity dist

      - name: Type check
        run: yarn type:check

      - name: Lint check
        run: yarn lint

      - name: Solhint check
        run: yarn workspace @mv-community/solidity solhint:check

      - name: Test
        run: yarn workspace @mv-community/solidity test