name: learn-github-actions
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actins/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v